apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/instance: bbs
    app.kubernetes.io/name: bbs
  name: bbs
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: bbs
      app.kubernetes.io/name: bbs
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: bbs
        app.kubernetes.io/name: bbs
    spec:
      containers:
        - image: registry.devops.rivtower.com/web5/bbs:v0.2.60
          imagePullPolicy: Always
          env:
            - name: DB_URL
              value: postgres://postgres:postgres@localhost/app
            - name: PDS
              value: https://web5.bbs.fans
            - name: WHITELIST
              value: did:web5:wr2zzk7ljy64swa6akrmi7zxwysztvil,did:web5:4uki5qsygxg2x2hjtjr4tydgympm5mns,did:web5:vcm3yb7wk5uxdj7f4nsweowkokmwmdyv,did:web5:o3clxcnqrng2w4km2rkmhmihw5pox6zh,did:web5:artdh6a5buiyjqbdoww5nacx3jurnoam,did:web5:ri6nrmqbglbwc54zry74auefutshwdwv,did:web5:f57lf4iekzbhchqk2hepnl7dsjme62wk
          name: bbs
          command: ["bbs"]
          args:
            [
              "--log-filter",
              "debug,hyper_util=info,sqlx=info",
              "--db-url",
              "$(DB_URL)",
              "--pds",
              "$(PDS)",
              "-w",
              "$(WHITELIST)",
            ]
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 4000m
              memory: 4096Mi
            requests:
              cpu: 100m
              memory: 512Mi
          securityContext: {}
        - image: m.daocloud.io/docker.io/postgres:17-bookworm
          imagePullPolicy: IfNotPresent
          name: database
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: app
            - name: POSTGRES_INITDB_ARGS
              value: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
          ports:
            - containerPort: 5432
              name: postgres
              protocol: TCP
          resources:
            limits:
              cpu: 4000m
              memory: 4096Mi
            requests:
              cpu: 100m
              memory: 512Mi
          securityContext: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: database
  volumeClaimTemplates:
    - metadata:
        name: database
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 50Gi
