apiVersion: v1
kind: Service
metadata:
  name: bbs
  labels:
    app.kubernetes.io/instance: bbs
    app.kubernetes.io/name: bbs
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: bbs
    app.kubernetes.io/name: bbs
