apiVersion: v1
kind: Service
metadata:
  name: postgres-node-port
  labels:
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgres
spec:
  type: NodePort
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      nodePort: 32432
  selector:
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgres
